### ISSUE TITLE
Handle more characters

### ISSUE THREAD

**Issue by SteveX** [donmccurdy/msdf-bmfont-web#11]
Could the maximum number of characters be increased slightly? 

It works ok for English (by removing punctuation), but not for languages which use accents (such as Portuguese) which uses an additional 12 characters. 

> ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzÀÁÂÃÉÈÍÓÔÕÚÇáàâãéêíóôõúç0123456789!"#'$%&()*+,-./:;?[\]^_`@=

**Comment by donmccurdy** [comment]
Where are you using the resulting font? A-Frame? I don’t think there’s a maximum number of characters in this tool but some engines may have these limits..

**Comment by donmccurdy** [comment]
Yeah, so the output of this tool does support as many characters as you want, but if you use enough characters the tool may need to output multiple textures. In this case you get 2 textures. Neither the preview in this tool, nor A-Frame, support more than 1 texture per font. So you'll want to remove characters until there's only one texture created, if you care about A-Frame. Ideally, use only characters you know your experience will need.

For the relevant issue in A-Frame, see https://github.com/aframevr/aframe/issues/3355.

Another option would be to tweak other settings in the font generation to reduce font _quality_ so that more letters fit in a single texture. This tool doesn't currently do that (https://github.com/donmccurdy/msdf-bmfont-web/issues/5) but you could use https://github.com/soimy/msdf-bmfont-xml to generate fonts and tweak settings however you need.

**Comment by SteveX** [comment]
It was for A-frame, msdf-bmfont-xml does the job. Thanks!

**Comment by donmccurdy** [comment]
Ok, good to hear! Do you mind sharing the msdf-bmfont-xml settings you needed to change, to solve your issue? Wondering which would be most important to provide in this tool.

**Comment by SteveX** [comment]
I'm still tweaking, there's lots of empty space on the png and in A-frame the text is shifted down slightly. This is what I used:

`msdf-bmfont -m 512,512 --square -p 0 -i  /Users/admin/Desktop/msdf-bmfont-xml-master/assets/charset/charset.custom.txt -f json /Users/admin/Downloads/roboto/Roboto-Regular.ttf`

**Comment by donmccurdy** [comment]
Ok thanks! I went ahead and added a texture size dropdown to the tool, should make this easier next time. :)
